apiVersion: v1
kind: Secret
metadata:
  name: {{ include "passbolt-helm.fullname" . }}-jwt
  labels:
{{ include "passbolt-helm.labels" . | indent 4 }}
  annotations:
    "helm.sh/hook-delete-policy": "before-hook-creation"
data:
  "jwt.key": {{ if .Values.passbolt.config.jwtkey }}{{ .Values.passbolt.config.jwtkey | b64enc | quote }}{{ else }}{{ .Files.Get "secrets/jwt/jwt.key" | b64enc | quote }}{{ end }}
  "jwt.pem": {{ if .Values.passbolt.config.jwtcert }}{{ .Values.passbolt.config.jwtcert | b64enc | quote }}{{ else }}{{ .Files.Get "secrets/jwt/jwt.pem" | b64enc | quote }}{{ end }}